CAYSTI/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from patientsApp import views as patientsAppviews


urlpatterns = [
    path('blog/', include('blog.url')),
    path('admin/', admin.site.urls),
    path('', views.home),
    path('page/', views.vaccination, name='vaccination'),
    path('presentation/', views.presentation, name= 'presentation'),
    path('symptômes/', views.symptomes, name='symptomes'),
    path('transmission/', views.mode_transmission, name='mode_transmission'),
    path('gestes barrières/', views.geste_barrieres, name='gestes_barrieres'),
    path('preventions/', views.preventions, name='preventions'),
    path('vaccination/', views.vaccination, name='vaccination'),
    path('différents vaccins/', views.differents_vaccins, name='differents_vaccins'),
    path('statistique/', views.statistiques, name='statistiques'),
    path('reservation/', views.reservation, name='reservation'),
    path('page/', views.about, name="home"),
    path('patientsApp/', patientsAppviews.register_patient, name="sign_up"),
    path('login/', patientsAppviews.sign_in, name="login"),


]

blog/models.py
'''from django.db import models
class Patient(models.Model):
    name=models.CharField(max_length=200)
    telephone = models.IntegerField(max_length=200)
    email=models.CharField(max_length=200, null=True)
    adress=models.TextField(max_length=500, null=True)
    sexe = models.CharField(max_length=200, null=True)
    date_naissance = models.DateTimeField(max_length=200)


class Doctor(models.Model):
    name = models.CharField(max_length=200)
    roll_no=models.CharField(max_length=300)
    email = models.CharField(max_length=200)
    adress = models.TextField(max_length=500)
    specialite = models.TextField(max_length=500)'''

patientsApp/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User, UserManager
from django.contrib.auth.models import (
        AbstractBaseUser, BaseUserManager, PermissionsMixin
)
from django.utils.translation import gettext as _
from django.core.validators import RegexValidator
from django.utils.timezone import now
'''definition des differents choix du sexe
... sex_choice=
        dictionnaire des differents choix de sexe.
'''


sex_choice = {
    ('FEMININ', 'feminin'),
    ('MASCULIN', 'masculin'),
}
'''
creation de notre model
creation de la classe Patients pour creer notre model
'''
class UserManager(BaseUserManager):
    def create_user(
            self,
            email,
            username,
            password,
            is_active=False,
            is_staff=False,
            is_admin=False,
            is_superuser=False
    ):
        if not email:
            raise ValueError("Users must have an email address")
        if not username:
            raise ValueError("Users must have an username")

        user = self.model(
            email = self.normalize_email(email),
            username = username,
            is_active = is_active,
            is_staff = is_staff,
            is_admin = is_admin,
            is_superuser = is_superuser
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    def create_superuser(self, email, username, password):
        return self.create_user(
            email=self.normalize_email(email),
            password=password,
            username=username,
            is_admin = True,
            is_staff = True,
            is_active = True,
            is_superuser=True
        )



class Utilisateur(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=200, unique=True, null=False)
    email = models.EmailField(max_length=200, unique=True, null=True)
    phone_regex = RegexValidator(regex=r"^\+?237?\d{9,15}$",
                                 message="Phone number must be entered in the format: '+237699968301'. Up to 15 digits allowed.")
    phone = models.CharField(validators=[phone_regex], max_length=17)
    address = models.CharField(max_length=500, default="")
    sex = models.CharField(max_length=200, default="", choices=sex_choice)
    birth_date = models.DateField(default="1995-5-10")
    password = models.CharField(_('password'), max_length=128, default="")

    date_joined = models.DateTimeField(default=now)
    created_at = models.DateTimeField(default=now)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    is_active = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    #is_supseruser = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD ='username'
    #REQUIRED_FIELDS = [ 'email', 'phone', 'address', 'sex', 'birth_date', 'password', ]
    REQUIRED_FIELDS = ['email']



    def __str__(self):
        return self.username
    # @property
    # def is_supervisor(self):
    #     return self.is_admin
    #
    # def has_perm(self, perm, obj=None):
    #     return self.is_admin




# Create your models here.
# class UtilisateurAdmin(admin.ModelAdmin):
#     list_display = ('phone', 'address', 'sex', 'birth_date')
#     list_filter = ('name',)
#     search_fields = ['name', 'email']

class Hopital(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    latitude = models.DecimalField(max_digits=30, decimal_places=20)
    longitude = models.DecimalField(max_digits=30, decimal_places=20)

class HopitalAdmin(admin.ModelAdmin):
    list_display = ('name', 'address')
    list_filter = ('name',)
    search_fields = ['name', 'address']

"""class Reservation(models.Model):
    hospital = models.forieng
    reservation_date = models.CharField(max_length=200)"""

"""
class ReservationAdmin(admin.ModelAdmin):
    list_display = ('hospital', 'reservation_date')
    list_filter = ('hospital',)
    search_fields = ['hospital', 'reservation_date']"""
# user = models.ForeignKey(User,
    #                          related_name="%(app_label)s_%(class)s_patient_id",
    #                          on_delete=models.CASCADE,
    #                          default=1)
  #  phone = models.IntegerField()

statistique/views.py
import sqlite3


# Function for Convert Binary Data
# to Human Readable Format
def convertToBinaryData(filename):
    # Convert binary format to images
    # or files data
    with open(filename, 'rb') as file:
        blobData = file.read()
    return blobData


def insertBLOB(id, date,  photo):
    try:

        # Using connect method for establishing
        # a connection
        sqliteConnection = sqlite3.connect('SQLite_Retrieving_data.db')
        cursor = sqliteConnection.cursor()
        print("Connected to SQLite")

        # insert query
        sqlite_insert_blob_query = """ INSERT INTO statistique
                                  (id, date, photo) VALUES (?, ?)"""

        # Converting human readable file into
        # binary data
        empPhoto = convertToBinaryData(photo)

        # Convert data into tuple format
        data_tuple = (date, empPhoto)

        # using cursor object executing our query
        cursor.execute(sqlite_insert_blob_query, data_tuple)
        sqliteConnection.commit()
        print("Image and file inserted successfully as a BLOB into a table")
        cursor.close()

    except sqlite3.Error as error:
        print("Failed to insert blob data into sqlite table", error)

    finally:
        if sqliteConnection:
            sqliteConnection.close()
            print("the sqlite connection is closed")


insertBLOB(1,"2021/09/08", "E:\python\caysti\static\caysti\image\8-sept221.png")
#insertBLOB("David", "D:\Internship Tasks\GFG\images\person.png")

templates/accueil.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: dodgerblue !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: white;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #54c1fb;

		}

		.login_btn {
			width: 100%;
			background: #54c1fb !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #54c1fb !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		.messages{
			background-color: green;
			color: #fff;
			padding: 5px;
			margin-top: 10px;
		}
		li{
		    list-style-type: none;
		}
	</style>

</head>
<body>

	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{%csrf_token%}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>
						<div id="message_success">
							{% if form.errors %}
								{% for field in form %}
									{% for error in field.errors %}
										<div class="alert alert-danger">
											<strong>{{ error|escape }}</strong>
										</div>
									{% endfor %}
								{% endfor %}
								{% for error in form.non_field_errors %}
									<div class="alert alert-danger">
										<strong>{{ error|escape }}</strong>
									</div>
								{% endfor %}
							{% endif %}

							{% if messages %}
							<ul class="messages">
								{% for message in messages %}
								<li {% if message.tags %} class="{{ message.tags }}"{% endif %}><center>{{ message }}</center></li>
								{% endfor %}
							</ul>
							{% endif %}</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="/patientsApp" class="ml-2">Sign Up</a>
					</div>

				</div>
			</div>
		</div>
	</div>

	<script>
		setTimeout(fade_out, 5000);

		function fade_out() {
 			 $("#message_success").fadeOut().empty();
			}
	</script>
</body>

</html>

templates/register_patient.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #54c1fb !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: white;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color:#54c1fb;
		}
		.login_btn {
			width: 100%;
			background: #54c1fb !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #54c1fb !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		#id_sex{
            display: flex;
            margin-left: -1px;
            box-sizing: border-box;
     		padding: 6px 12px;
            line-height: 1;
            width: 201px;
			border-radius: 3px;
			color: #495057 !important;
			border: 1px solid #ced4da !important;

			}
		 .input-group-append#id_email{
            display: flex;
            margin-left: -1px;
            box-sizing: border-box;
            font-size: 1.4rem;
            font-weight: 500;
            line-height: 1;
        }
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-phone"></i></span>
							</div>
							{{form.phone}}
						</div>
						 <div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-address-card"></i></span>
							</div>
                            {{form.address}}
                        </div>
						 <div class="input-group mb-2"style="background-color: white; border-radius: 3px;    line-height: 2.3qu;" >
							<div class="input-group-append" style="font-size: 1.4rem;font-weight: 500; line-height: 1;display: flex;
																	margin-left: -1px;
																	box-sizing: border-box;">
								<span class="input-group-text"><i class="fas fa-venus-mars" ></i></span>
							</div>
							<div style="cursor: pointer;color: white;font-size: 1rem; flex-grow: 1; ">
                            {{form.sex}}
							</div>
                        </div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text" style=""><i class="fa fa-calendar" aria-hidden="true"></i></span>
							</div>
                            {{form.birth_date}}
                        </div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>



				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>

					</form>
				</div>

				{{form.errors}}
				
				<div class="mt-4">
					<div class="d-flex justify-content-center links" id="else">
						Already have an account? <a href="/login" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Phone..';
		form_fields[4].placeholder='Address..';
		form_fields[5].placeholder='Birth_date..';
		form_fields[6].placeholder='Enter password...';
		form_fields[7].placeholder='Re-enter Password...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>